// Mocks generated by Mockito 5.4.5 from annotations
// in coding_interview_dorado/test/unit/presentation/providers/currency_exchange_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coding_interview_dorado/features/currency_exchange/domain/entities/exchange_rate_entity.dart'
    as _i2;
import 'package:coding_interview_dorado/features/currency_exchange/domain/usecases/get_exchange_rate_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExchangeRateEntity_0 extends _i1.SmartFake
    implements _i2.ExchangeRateEntity {
  _FakeExchangeRateEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetExchangeRateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExchangeRateUseCase extends _i1.Mock
    implements _i3.GetExchangeRateUseCase {
  MockGetExchangeRateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExchangeRateEntity> call({
    required int? type,
    required String? cryptoCurrencyId,
    required String? fiatCurrencyId,
    required double? amount,
    required String? amountCurrencyId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #type: type,
            #cryptoCurrencyId: cryptoCurrencyId,
            #fiatCurrencyId: fiatCurrencyId,
            #amount: amount,
            #amountCurrencyId: amountCurrencyId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ExchangeRateEntity>.value(_FakeExchangeRateEntity_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #type: type,
              #cryptoCurrencyId: cryptoCurrencyId,
              #fiatCurrencyId: fiatCurrencyId,
              #amount: amount,
              #amountCurrencyId: amountCurrencyId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ExchangeRateEntity>);
}
